### ISSUE TITLE
plugin not loading correctly: FACSHuman 0.1 and FACS Animation Tool menus missing

### ISSUE THREAD

**Issue by crystal-butler** [montybot/FACSHuman#7]
This might be a duplicate of issue #6, but @eioe doesn't specify exactly what the solution was, and I'm unable to find any errors in my installation. The FACS Scene Editor loads but the FACSHuman 0.1 and FACS Animation Tool menus are not available.
<img width="1792" alt="Screen Shot 2021-07-25 at 7 09 32 PM" src="https://user-images.githubusercontent.com/1704599/126916845-c70d4bd1-909b-4901-8e92-efba84a4805f.png">

I'm running the latest FACSHuman under MakeHuman 1.2.0 on a Mac. Per issue #6, I checked the following:
- activate plugins: the FACSHuman python scripts were added to `/Applications/MakeHuman.app/Contents/Resources/makehuman/plugins` and show up in the Plugins menu, but there is no option to activate plugins there. The User Plugins menu has an option to activate plugins, but no plugins are listed (and I didn't see a user plugins directory at the same level as `plugins`.
<img width="1792" alt="Screen Shot 2021-07-25 at 7 05 36 PM" src="https://user-images.githubusercontent.com/1704599/126916651-918d235b-6f7a-4d37-b767-0c3ca7044fae.png">
- logs: warnings are as follows
<img width="1791" alt="Screen Shot 2021-07-25 at 7 06 04 PM" src="https://user-images.githubusercontent.com/1704599/126916738-b79a6705-ee30-480e-8a20-ace650b0166a.png">

Here are shots of my directory structure for the AU target files and plugin scripts:
<img width="1773" alt="Screen Shot 2021-07-25 at 7 07 03 PM" src="https://user-images.githubusercontent.com/1704599/126916792-92bea451-20c8-4412-832e-da33caf663cd.png">
<img width="1443" alt="Screen Shot 2021-07-24 at 4 24 07 PM" src="https://user-images.githubusercontent.com/1704599/126916797-7b743f2e-eb2d-4cb6-947e-7bd62b19ef77.png">

Please let me know if you have any more information on what fixed @eioe's problem or can suggest other troubleshooting steps--thanks!

**Comment by crystal-butler** [comment]
I tried removing the python scripts from `plugins` and importing them in the User Plugins menu directly in MakeHuman, then activating the plugins. I get the same `Not a directory` error in reference to `au.json` as before.

**Comment by eioe** [comment]
Hey @crystal-butler , although the error log looks the same as for me (`au.json` not found), my "fix" won't do it for you. As I wrote, I had simply set up the folder structure incorrectly (I had one "layer" of `FACSHuman` folders too much). That looks ok in your setup. 
I'm not experienced with Mac, but it looks like `...\\v1py3\data\FACSHuman` (and a few others) are symlinks. Maybe that's a problem?

**Comment by crystal-butler** [comment]
@eioe, you are exactly right. Mac created symlinks instead of moving the directories because of the location I had stored my original clone of FACSHuman-master. Explicitly creating copies to replace the symlinked directories fixed the problem--thanks!
